language: python

python:
  - "2.7"

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly
  #- sudo apt-get update
  #- sudo apt-get install openoffice.org python-genshi python-cairo python-openoffice python-lxml python-uno
  #- sudo apt-get install zip
  #- bzr branch lp:aeroolib /tmp/aeroolib
  #- bzr branch lp:aeroo /tmp/aeroo
  #- pushd /tmp/aeroolib/aeroolib; sudo python setup.py install; popd

script:
    - travis_run_tests

after_success:
  coveralls
