[project]
name = "odoo-addons-oca-hr"
version = "17.0.20231116.0"
dependencies = [
    "odoo-addon-hr_employee_firstname>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
